export const ADD_PRODUCT = "ADD_PRODUCT";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export const DECREASE_AMOUNT_PRODUCT = "DECREASE_AMOUNT_PRODUCT";

export const INCREASE_AMOUNT_PRODUCT = "INCREASE_AMOUNT_PRODUCT";

export const UPDATE_PRODUCT = "REMOVE_PRODUCT";

export const SET_CURRENCY = "SET_CURRENCY";
